import type { Athlete, BbchEvent, Result } from "./types";
import eventsRaw from "@/data/generated/events.json";
import athletesRaw from "@/data/generated/athletes.json";
import resultsRaw from "@/data/generated/results.json";

/* ------------------------------------------------------------------ *
 * Real data, imported from the historic archive (2015–2026).
 * Generated by the importer from the "All Race Results" Excel files.
 * ------------------------------------------------------------------ */

const NAME_EXPAND: Record<string, string> = {
  xc: "Cross-Country (XC)",
  xco: "Cross-Country (XC)",
  itt: "Individual Time Trial",
  ttt: "Team Time Trial",
  "ttt & itt": "Team & Individual Time Trial",
  cx: "Cyclocross",
  dh: "Downhill",
  crit: "Criterium",
  "dh-xc": "Downhill & Cross-Country",
};

function prettyName(rawName: string, year: number, raceNo: number): string {
  // Strip "Race #04 - " / "BBCh 09 - " style prefixes
  let base = rawName.replace(/^Race\s*#?\s*\d+\s*[-–]\s*/i, "").trim();
  base = base.replace(/^BBCh\s*\d+\s*[-–]\s*/i, "").trim();
  if (!base) base = rawName;

  base = base.replace(/\bBLR\b/i, "Bangalore");
  const expanded = NAME_EXPAND[base.toLowerCase()];
  if (expanded) base = expanded;

  // Prefix with the race number so multiple same-discipline races in a
  // season are distinguishable (e.g. three "Cross-Country (XC)" races).
  const racePart = raceNo >= 1 && raceNo <= 30 ? `Race ${raceNo} — ` : "";
  return `${racePart}${base} · ${year}`;
}

export const events: BbchEvent[] = (eventsRaw as Array<Omit<BbchEvent, "slug" | "name" | "rawName"> & { name: string }>)
  .map((e) => ({
    ...e,
    rawName: e.name,
    slug: e.id,
    name: prettyName(e.name, e.year, e.raceNo),
  }))
  .sort((a, b) => (a.year !== b.year ? b.year - a.year : b.raceNo - a.raceNo));

export const athletes: Athlete[] = athletesRaw as Athlete[];
export const results: Result[] = resultsRaw as Result[];

/* -------- indexes -------- */
const eventById = new Map(events.map((e) => [e.id, e]));
const athleteById = new Map(athletes.map((a) => [a.id, a]));
const athleteBySlug = new Map(athletes.map((a) => [a.slug, a]));

const resultsByEvent = new Map<string, Result[]>();
const resultsByAthlete = new Map<string, Result[]>();
for (const r of results) {
  (resultsByEvent.get(r.eventId) ?? resultsByEvent.set(r.eventId, []).get(r.eventId)!).push(r);
  (resultsByAthlete.get(r.athleteId) ?? resultsByAthlete.set(r.athleteId, []).get(r.athleteId)!).push(r);
}

/* -------- event helpers -------- */
export function getEvents(): BbchEvent[] {
  return events;
}
export function getRecentEvents(n = 6): BbchEvent[] {
  return events.slice(0, n);
}
export function getEventBySlug(slug: string): BbchEvent | undefined {
  return eventById.get(slug);
}
export function getEventById(id: string): BbchEvent | undefined {
  return eventById.get(id);
}
export function getSeasons(): number[] {
  return [...new Set(events.map((e) => e.year))].sort((a, b) => b - a);
}

/* -------- athlete helpers -------- */
export function getAthleteBySlug(slug: string): Athlete | undefined {
  return athleteBySlug.get(slug);
}
export function getAthleteById(id: string): Athlete | undefined {
  return athleteById.get(id);
}

/* -------- joined rows -------- */
export interface ResultRow extends Result {
  athlete: Athlete;
  event: BbchEvent;
}

function hydrate(r: Result): ResultRow | null {
  const athlete = athleteById.get(r.athleteId);
  const event = eventById.get(r.eventId);
  if (!athlete || !event) return null;
  return { ...r, athlete, event };
}

/** Sort finishers by rank; DNF/DNS to the bottom. */
function byRank(a: Result, b: Result): number {
  if (a.rank == null && b.rank == null) return 0;
  if (a.rank == null) return 1;
  if (b.rank == null) return -1;
  return a.rank - b.rank;
}

export function getResultsForEvent(eventId: string): ResultRow[] {
  return (resultsByEvent.get(eventId) ?? [])
    .slice()
    .sort(byRank)
    .map(hydrate)
    .filter((r): r is ResultRow => r !== null);
}

export function getResultsForAthlete(athleteId: string): ResultRow[] {
  return (resultsByAthlete.get(athleteId) ?? [])
    .map(hydrate)
    .filter((r): r is ResultRow => r !== null)
    .sort((a, b) =>
      a.event.year !== b.event.year
        ? b.event.year - a.event.year
        : b.event.raceNo - a.event.raceNo
    );
}

/* -------- lean rows for the client-side search (small payload) -------- */
export interface SearchRow {
  id: string;
  athleteName: string;
  athleteSlug: string;
  gender: string;
  eventId: string;
  eventName: string;
  eventSlug: string;
  year: number;
  category: string;
  discipline: string;
  rank: number | null;
  status: string | null;
  timeSeconds: number | null;
}

export function getSearchRows(): SearchRow[] {
  const rows: SearchRow[] = [];
  for (const r of results) {
    const a = athleteById.get(r.athleteId);
    const e = eventById.get(r.eventId);
    if (!a || !e) continue;
    rows.push({
      id: `${r.eventId}-${r.athleteId}-${r.category}`,
      athleteName: a.name,
      athleteSlug: a.slug,
      gender: a.gender,
      eventId: e.id,
      eventName: e.name,
      eventSlug: e.slug,
      year: e.year,
      category: r.category,
      discipline: r.discipline,
      rank: r.rank,
      status: r.status,
      timeSeconds: r.timeSeconds,
    });
  }
  return rows.sort((a, b) =>
    a.year !== b.year ? b.year - a.year : (a.rank ?? 9999) - (b.rank ?? 9999)
  );
}

/* -------- stats & bests -------- */
/** BBCh was founded in 2008 — predates the digitized results archive (2015–). */
export const FOUNDING_YEAR = 2009;
/** Stated directly rather than computed — confirm/update this figure with BBCh each season. */
export const YEARS_RUNNING = 16;

export function getStats() {
  return {
    athletes: athletes.length,
    events: events.length,
    results: results.length,
    seasons: getSeasons().length,
    yearsRunning: YEARS_RUNNING,
  };
}

export function getPersonalBest(athleteId: string): ResultRow | null {
  const rows = getResultsForAthlete(athleteId).filter((r) => r.rank != null);
  if (rows.length === 0) return null;
  return rows.reduce((best, r) => (r.rank! < best.rank! ? r : best), rows[0]);
}

export function getTopCategories(): string[] {
  const c = new Map<string, number>();
  for (const r of results) c.set(r.category, (c.get(r.category) ?? 0) + 1);
  return [...c.entries()].sort((a, b) => b[1] - a[1]).map(([k]) => k);
}

export function getDisciplines(): string[] {
  return [...new Set(events.map((e) => e.discipline))].sort();
}

export interface AthleteSummary {
  id: string;
  slug: string;
  name: string;
  team: string | null;
  gender: string;
  races: number;
  wins: number;
  bestRank: number | null;
  imageUrl?: string;
}

export function getAthleteSummaries(): AthleteSummary[] {
  return athletes
    .map((a) => {
      const rows = resultsByAthlete.get(a.id) ?? [];
      const ranks = rows.map((r) => r.rank).filter((r): r is number => r != null);
      return {
        id: a.id,
        slug: a.slug,
        name: a.name,
        team: a.team ?? null,
        gender: a.gender,
        races: rows.length,
        wins: ranks.filter((r) => r === 1).length,
        bestRank: ranks.length ? Math.min(...ranks) : null,
        imageUrl: a.imageUrl,
      };
    })
    .sort((a, b) => b.races - a.races || a.name.localeCompare(b.name));
}
